---
# tasks file for ans-vault

- name: Install Hashicorp Key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Install Hashicorp Repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
    state: present
    
- name: Install Vault
  apt:
    name: vault
    update_cache: yes

